---
title: "Course Schedule"
tbl-colwidths: [5,5,10,5,5,5,5]
editor: visual
---

```{r}
#| label: setup
#| include: false

source("helper.R")
```

This page displays an outline of the topics, content, and assignments for the term. Each module starts on a Monday. There are no assignments due on weekends.

::: column-screen-inset-right
| Module | Date | Topic | Readings | Slides | Videos | Assignments |   |
|---------|---------|---------|---------|---------|---------|---------|---------|
| [GS](modules/getting-started.qmd "Getting started") | By `r advdate(mon,0)` | Before We Begin | [📖](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/ "project workflow post") |  | [🖥️](https://youtu.be/eimM6pNkYjE), [🖥️](https://youtu.be/6QN9ZYURDFg) |  |  |
| [1.1](modules/module-1.1.qmd "Module 1.1") | `r advdate(mon,0)` | Course overview | [📖](https://r4ds.hadley.nz/data-import "r4ds, chap. 7"), [📖](https://r4ds.hadley.nz/data-visualize.html "r4ds, chap. 2") | [🖥️](slides/week-1.1.qmd "Module 1.1 slides") | [🖥️](https://youtu.be/QG1oDJPoIio), [🖥️](https://youtu.be/-1YhCql-gMo) |  |  |
| [1.2](modules/module-1.2.qmd "Module 1.2") | `r advdate(wed,0)` | Basics of data viz | [📖](https://r4ds.hadley.nz/layers.html "r4ds, chap. 10.1-10.4"), [📖](https://r4ds.hadley.nz/communication.html#labels "r4ds, chap. 12.2") | [🖥️](slides/week-1.2.qmd "Module 1.2 slides") | [🖥️](https://youtu.be/PnmQ2MFQpIc), [🖥️](https://youtu.be/FiosjUVyfLM) | [🧪](/labs/lab-1/lab1.html "Lab 1") |  |
| [2.1](modules/module-2.1.qmd "Module 2.1") | `r advdate(mon,1)` | Wrangling data | [📖](https://r4ds.hadley.nz/data-transform.html#introduction "r4ds, 3.1 - 3.4") | [🖥️](slides/week-2.1.html "Module 2.1 slides") | [🖥️](https://youtu.be/ScQD47eJeAE) |  |  |
| [2.2](modules/module-2.2.qmd "Module 2.2") | `r advdate(wed,1)` | Exploring categorical data | [📖](https://www-jstor-org.proxygw.wrlc.org/stable/1951731?seq=8 "Lipset"), [📖](https://r4ds.hadley.nz/data-transform.html#groups "r4ds, 3.5") | [🖥️](slides/week-2.2.html "Module 2.2 slides") | [🖥️](https://youtu.be/mgBwVzMV-v8) | [🧪](/labs/lab-2/lab2.html "Lab 2"), [🧮](/assignments/homework-1.html "Homework 1") |  |
| [3.1](modules/module-3.1.qmd "Module 3.1") | `r advdate(mon,2)` | Continuous distributions | [📖](https://openintro-ims.netlify.app/explore-categorical "IMS, Ch. 4"), [📖](https://openintro-ims.netlify.app/explore-numerical "IMS, Ch. 5") | [🖥️](slides/week-3.1.qmd "Module 3.1 slides") | [🖥️](https://youtu.be/7NhNeADL8fA?si=InH8FFc1BIVT0ktM), [🖥️](https://youtu.be/Xm0PPtci3JE?si=MocqDt05YqllA9k5) |  |  |
| [3.2](modules/module-3.2.qmd "Module 3.2") | `r advdate(wed,2)` | Sampling and Uncertainty | [📖](https://openintro-ims.netlify.app/foundations-randomization "IMS, Ch. 11"), [📖](https://openintro-ims.netlify.app/foundations-bootstrapping "IMS, Ch. 12") | [🖥️](slides/week-3.2.qmd "Module 3.2 slides") | [🖥️](https://www.youtube.com/watch?v=5q2ac412hv4), [🖥️](https://youtu.be/Xz0x-8-cgaQ?si=v_YCi-dU5YBdcb99) | [🧪](/labs/lab-3/lab3.html "Lab 3") |  |
| [4.1](modules/module-4.1.qmd "Module 4.1") | `r advdate(mon,3)` | Hypothesis testing 1 | [📖](https://openintro-ims.netlify.app/inference-one-prop "IMS, ch. 16") | [🖥️](slides/week-4.1.qmd "Module 4.1 slides") | [🖥️](https://www.youtube.com/watch?v=cn4S3QqEBRg) |  |  |
| [4.2](modules/module-4.2.qmd "Module 4.2") | `r advdate(wed,3)` | Hypothesis testing 2 | [📖](https://academic.oup.com/qje/article-abstract/127/4/1755/1841616 "Casey et al."), [📖](https://openintro-ims.netlify.app/inference-two-means "IMS, ch. 20") | [🖥️](slides/week-4.2.qmd "Module 4.2 slides") | [🖥️](https://youtu.be/rJ3AZCQuiLw?si=ouSZSRXxn-OD9isj) | [🧪](/labs/lab-4/lab4.html "Lab 4"), [🧮](/assignments/homework-2.html "Homework 2") |  |
| [5.1](modules/module-5.1.qmd "Module 5.1") | `r advdate(mon,4)` | Linear regression | [📖](https://openintro-ims.netlify.app/model-slr "IMS, chap. 7") | [🖥️](slides/week-5.1.qmd "Module 5.1 slides") | [🖥️](https://youtu.be/dLc-lfEEYss?si=-Zelb-HBAP-MPvnF), [🖥️](https://youtu.be/KWULpBYzIYk?si=z_-wmdYlyrdpN4ys) |  |  |
| [5.2](modules/module-5.2.qmd "Module 5.2") | `r advdate(wed,4)` | Multiple regression | [📖](https://openintro-ims.netlify.app/model-mlr "IMS, chap. 8") | [🖥️](slides/week-5.2.qmd "Module 5.2 slides") | [🖥️](https://youtu.be/jXg0vU0y1ak?si=rhQ9uWhuhVqnI-Ox) | [🧪](/labs/lab-5/lab5.html "Lab 5") |  |
| [6.1](modules/module-6.1.qmd "Module 6.1") | `r advdate(mon,5)` | Logistic regression | [📖](https://openintro-ims.netlify.app/model-logistic "IMS, chap. 9") | [🖥️](slides/week-6.1.qmd "Module 6.1 slides") | [🖥️](https://youtu.be/p-ltr1C7u2o?si=TLb3y75pSaJ067ue), [🖥️](https://youtu.be/xuTiAW0OR40?si=sUoIr5pzHwHEpazO) |  |  |
| [6.2](modules/module-6.2.qmd "Module 6.2") | `r advdate(wed,5)` | Presenting results | [📖](https://journals.sagepub.com/doi/10.1177/0022343316684009 "Blair et al.") | [🖥️](slides/week-6.2.qmd "Module 6.2 slides") | [🖥️](https://youtu.be/oIR8YOSXudM?si=aEALe2ifW71lsJJG), [🖥️](https://youtu.be/upn8dlhvbns), [🖥️](https://youtu.be/My6_X6x5TZw), [🖥️](https://youtu.be/gif_wkqyub8) | [🧪](/labs/lab-6/lab6.html "Lab 6"), [🧮](/assignments/homework-3.html "Homework 3") |  |
:::